function colorScreen(img1, img2, RGB, tol)
    ext = img1(end-3:end);
    newName = [img1(1:end-4) '_new' ext];
    redTol = [RGB(1) - tol, RGB(1) + tol];
    greenTol = [RGB(2) - tol, RGB(2) + tol];
    blueTol = [RGB(3) - tol, RGB(3) + tol];
    im1 = imread(img1);
    im2 = imread(img2);
    r1 = im1(:,:,1);
    r2 = im2(:,:,1);
    g1 = im1(:,:,2);
    g2 = im2(:,:,2);
    b1 = im1(:,:,3);
    b2 = im2(:,:,3);
    [rows,cols,~] = size(im1);
    newR = 255.*ones(rows,cols);
    newG = newR;
    newB = newR;
    redLow = r2 >= redTol(1);
    greenLow = g2 >= greenTol(1);
    blueLow = b2 >= blueTol(1);
    redHi = r2 <= redTol(2);
    greenHi = g2 <= greenTol(2);
    blueHi = b2 <= blueTol(2);
    red = redLow & redHi;
    green = greenLow & greenHi;
    blue = blueLow & blueHi;
    match = red & green & blue;
    newR(match) = r1(match);
    newR(~match) = r2(~match);
    newG(match) = g1(match);
    newG(~match) = g2(~match);
    newB(match) = b1(match);
    newB(~match) = b2(~match);
    newIm = uint8(cat(3,newR,newG,newB));
    imwrite(newIm,newName);
end